node:
  image: matto/color-wander
  volumes:
    - node:/usr/src/app
  ports:
    - "8080:9966"
    - "35729:35729"
  command: npm run start
  env_file:
    - ./common.env

notebook:
  image: matto/portrait
  volumes:
    - ./images:/images
    - ./data:/data
  links:
    - node:portrait-service
  ports:
    - "443:8888"
  env_file:
    - ./common.env
