node:
  image: matto/color-wander
  ports:
    - "8080:9966"
    - "35729:35729"
  command: npm run start

notebook:
  image: matto/portrait
  volumes:
    - ./images:/images
    - ./data:/data
  links:
    - node
  ports:
    - "443:8888"
